### ISSUE TITLE
Native `final`

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#13]
Need some meta to mark classes/methods as [final](http://php.net/manual/en/language.oop5.final.php)

_Implemented in 5d70de2 and e83633e_

**Comment by mockey** [comment]
There is `@:final` already (not implemented for PHP).

**Comment by RealyUniqueName** [comment]
Actually it's not the same.
Haxe `@:final` can be ignored with `@:hack`

**Comment by mockey** [comment]
Is this a problem? Maybe not implement `@:hack` then?

**Comment by RealyUniqueName** [comment]
But it exists and promised to be crossplatform thus should be implemented https://haxe.org/manual/cr-metadata.html

**Comment by mockey** [comment]
It's just for classes that get generated, so it just overrides `@:final` in haxe code not real `final`, no?

**Comment by RealyUniqueName** [comment]
``` haxe
@:final class A {}
@:hack class B extends A {}
```

Is perfectly fine for Haxe and will be generated 

``` php
final class A {}
class B extends A {}
```

Which will cause a runtime error.

**Comment by mockey** [comment]
I see. Never used this (or even thought about it).
So: detect @:hack, lookup parent class, remove @:final. Possible before actual code generation?
Maybe check other generators. Should be tthe same problem for other targets.

**Comment by RealyUniqueName** [comment]
Removing `@:final` if someone is `@:hack`-ing it might be a solution.
