### ISSUE TITLE
PHP keywords in identifiers

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#14]
Implement a solution to allow PHP keywords to be used as identifiers in Haxe code.

**Comment by mockey** [comment]
Yes, important also for namepaces and class names. Probably have to consider all these:
http://php.net/manual/en/reserved.php

**Comment by RealyUniqueName** [comment]
Note: variables and class vars (everything starting with `$`) can use php keywords.

**Comment by RealyUniqueName** [comment]
_Absorbed by #47_
