### ISSUE TITLE
Uncaught exceptions handler

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#21]
_Implemented in 5c465cf_

PHP provides an ability to globally handle uncaught exceptions.
Need to implement access to this function from Haxe side.
http://php.net/manual/en/function.set-exception-handler.php

**Comment by mockey** [comment]
Should be similar to error handler.
There were some changes to exception handling in PHP7, though:
https://trowski.com/2015/06/24/throwable-exceptions-and-errors-in-php7/

**Comment by RealyUniqueName** [comment]
I wonder if we can flawlessly detect php version at startup and [alias](http://php.net/manual/en/function.class-alias.php) `Throwable` to `Exception` if php is pre 7

**Comment by mockey** [comment]
I wonder if it makes sense at all to support PHP pre 7.
But detection and aliasing should be possible. Or a compiler flag?

**Comment by RealyUniqueName** [comment]
_Implemented in 5c465cf_
