### ISSUE TITLE
Haxe code positions in exceptions trace

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#23]
Consider implementing sourcemaps to make runtime exceptions trace Haxe positions in call stack.
Inspired by http://lib.haxe.org/p/jstack/

**Comment by ConfidantCommunications** [comment]
Great idea.

**Comment by RealyUniqueName** [comment]
Done. Use `-lib jstack` to get Haxe positions in exceptions and call stacks.
