### ISSUE TITLE
Handle --php-prefix compiler flag

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#3]
`--php-prefix` should be used as additional top-level namespace for generated app.
When `--php-prefix` is used there should be no Haxe-generated php code in root namespace.

Example usage: `--php-prefix some.pack` will generate everything in `\some\pack` namespace.

_Related commits: 463667a_
_Implemented in c584f61_

**Comment by mockey** [comment]
Maybe it's a good idea to have an own namespace for Haxe generated code generally or for the std lib at least. A Date class in root is always bound for trouble.

**Comment by RealyUniqueName** [comment]
_Implemented in c584f61_
