### ISSUE TITLE
namespacing all core function in boot php class

### ISSUE THREAD

**Issue by francescoagati** [RealyUniqueName/haxe#30]
In current php version enum is compiled to class php Enum that go in conflict with enum class of silverstripe.
All the core and function class of haxe should be namespaced

**Comment by RealyUniqueName** [comment]
Such conflicts should be resolved with `--php-prefix` #3
Feel free to reopen if you need another solution.

**Comment by francescoagati** [comment]
Mmm no in current haxe php target enum isn't prefixed with enum

**Comment by francescoagati** [comment]
All inside this file isn't prefixed https://github.com/HaxeFoundation/haxe/blob/development/std/php/Boot.hx

**Comment by RealyUniqueName** [comment]
I mean in new php generator everything should be prefixed when `--php-prefix` specified.

**Comment by francescoagati** [comment]
Ok :-) thanks
