### ISSUE TITLE
Implement dynamic functions

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#31]
``` haxe
static dynamic function test() {
    return "original";
}
```

https://haxe.org/manual/class-field-dynamic.html

_Implemented in b53d973 and 7a84d558_

**Comment by mockey** [comment]
Yes, this is only one feature of a whole list of dynamic features that must be supported. From my experience a look at the old genphp sometimes gives some reasonable solutions for these.

**Comment by RealyUniqueName** [comment]
Yes, i look into old genphp a lot )

**Comment by mockey** [comment]
This dynamic stuff is pretty tricky, I had a go at this with Simn once. It would be good to have a list of all the stuff that needs to be supported. There are only the unit tests so far.
