### ISSUE TITLE
@:phpGlobal for externs for global functions

### ISSUE THREAD

**Issue by mockey** [RealyUniqueName/haxe#34]
How about it?
E.g. take all the functions from here:
http://php.net/manual/en/ref.var.php
and stuff them into:

``` haxe
@:phpGlobal extern class Var {
  static function is_array(o:Dynamic):Bool;
  ...
}
```

And then write `Var.is_array(arr)` instead of `untyped __call__("is_array", arr)`, but with completion and type-check.

**Comment by RealyUniqueName** [comment]
I don't think we need all of them. Especially those working with types. 
Instead we can pick some of them which could be really useful.

**Comment by RealyUniqueName** [comment]
I'm not sure if all of them should be in public classes. It can be really helpful for haxe->php dev, but how much do you use `untyped __call__` as haxe->php user?

**Comment by mockey** [comment]
> I'm not sure if all of them should be in public classes.

That's a general decision, how much of the native PHP API you want to expose. It was just an idea, the global functions are there, they are sorted in a way and they are documented, why not generate externs to some of them at least.

> It can be really helpful for haxe->php dev, but how much do you use untyped **call** as haxe->php user?

Depends on the use case. I use quite a lot native PHP classes (SoapClient e.g.) or functions (pspell, apcu, e.g.), and I already wrote externs for them.

But of course you could also pick certain important functions and stuff them in an extern class. Still some `@:phpGlobal` metadata that simply avoids generating `Class::` for extern static functions might be useful.

**Comment by RealyUniqueName** [comment]
Implemented in dd7cebd.

If extern class has `@:phpGlobal` meta then static methods translated to global functions and static vars translated to global constants. (see commit for examples)

**Comment by mockey** [comment]
Cool.
But I think the name for `Const` is not ideal in the long run. Why not `ErrorConstant`?
Also constants like this could be implemented as abstract enums, see my comment:
https://github.com/RealyUniqueName/haxe/issues/12#issuecomment-239915707
Not sure if this is a big advantage, though. Pattern matching maybe...

**Comment by RealyUniqueName** [comment]
Think about current `Global` and `Const` as temporary externs for development purposes )

**Comment by mockey** [comment]
I will :-)
