### ISSUE TITLE
@:coreType causes the compiler to hang

### ISSUE THREAD

**Issue by mockey** [RealyUniqueName/haxe#38]
see #37

**Comment by RealyUniqueName** [comment]
According to [docs](https://haxe.org/manual/types-abstract-core-type.html) `@:coreType` abstracts should not have underlying type.

**Comment by mockey** [comment]
Yes, I know. But this causes the generator to hang.
`@:coreType abstract NativeArray<T>` hangs..
`abstract NativeArray<T>(Dynamic)` works.

**Comment by RealyUniqueName** [comment]
Oh, now i get it )

**Comment by mockey** [comment]
The compiler just hangs when `generating php`, no error message or so.

**Comment by RealyUniqueName** [comment]
Did you try adding `@:runtimeValue`? https://haxe.org/manual/cr-metadata.html

**Comment by mockey** [comment]
No. Is this a runtimeValue? I don't know.
But I have a similar setup, that runs with old genphp (with `@:coreType` and all).

**Comment by RealyUniqueName** [comment]
Dynamic is a parametrized asbtract without underlying type. And it works:

``` haxe
@:coreType @:runtimeValue abstract Dynamic<T> {}
```

**Comment by mockey** [comment]
I tried `@:coreType @:runtimeValue abstract NativeArray<T>` and the compiler also hangs.
I'm not especially fond of `@coreType`, it's just that I used it without any problems before...

**Comment by RealyUniqueName** [comment]
I think i know what's the reason. Will fix it  later today.

**Comment by RealyUniqueName** [comment]
I can't reproduce this bug. Can you provide a minimal example code?

**Comment by mockey** [comment]
Did you uncomment `@coreType` on `NativeArray`?
Or define any other `@coreType abstract`?

**Comment by RealyUniqueName** [comment]
I did both

**Comment by RealyUniqueName** [comment]
Nevermind. I tried again and reproduced this issue

**Comment by RealyUniqueName** [comment]
_Fixed in 51a9650_
