### ISSUE TITLE
Pass static method as value

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#41]
Haxe

``` haxe
class Test {
  static function some () return 'hello';

  static function main () {
    return Test::some;
  }
}
```

PHP

``` php
class Test {
  static function some () {
    return 'hello';
  }

  static function main () {
    return function() { return Test::some(); };
  }
}
```

_Approach has been changed in 5776b8d:_

``` php
class Test {
  static function some () {
    return 'hello';
  }

  static function main () {
    return new HxClass(Test::class, 'some');
  }
}
```

**Comment by RealyUniqueName** [comment]
_Implemented in 9159b64. Implementation changed in 5776b8d_

**Comment by nadako** [comment]
> Implemented in 9159b64

you know you can just add `closes #41` to the commit message and have it closed automatically

**Comment by RealyUniqueName** [comment]
I know. But what will happen when these commit messages migrate to HF/haxe repo? Is it ok to reference a fork in a history of original repo?

**Comment by nadako** [comment]
That's a good question :)

**Comment by RealyUniqueName** [comment]
It will be confusing to go to issue 41 and find completely unrelated things )
