### ISSUE TITLE
NativeArray

### ISSUE THREAD

**Issue by mockey** [RealyUniqueName/haxe#42]
> :@:coreType @:runtimeValue NativeArray {
>   @:arrayAccess function get (key:Dynamic);

Now, that's pretty close to my implementation, only @:coreType and @:arrayAccess don't seem to work ATM: https://github.com/HaxeFoundation/haxe/issues/5525

For the time being I'd suggest:

``` haxe
abstract NatveArray(Dynamic) {
  @:arrayAccess inline function get<T>(key:EitherType<Int,String>):T
    return this[key];
  @:arrayAccess inline function set<T>(key:EitherType<Int,String>, val:T)
    this[key] = val;
}
```

Note that an array key can only be int or string, also I think T is always better than Dynamic.
And I'd like to add some array functions to the abstract, like `public inline function count`.

> abstract NativeArrayNum<T>(NativeArray)

I don't like Num here. How about `NativeAssocArray` and `NativeIndexedArray` as names?

_Implemented in 09f84aa_

**Comment by RealyUniqueName** [comment]
`@:arrayAccess` is not a type-level meta unlike you wrote in https://github.com/HaxeFoundation/haxe/issues/5525. 
It should be added to methods. Did you try this?

``` haxe
@:coreType @:runtimeValue NativeArray {
  @:arrayAccess function get (key:Dynamic) : Dynamic;
  @:arrayAccess function set (key:Dynamic, value:Dynamic) : Dynamic;
}
```

I'm convinced `NativeAvrray` should not be generic since it's a direct access to platform feature. And we should stick as close to platform behavior here as possible. And In PHP you can push anything in array. Also keys are dynamic, because in PHP you can use any scalar type as a key.

But with `NativeAssocArray` and `NativeIndexedArray` i completely agree with you. They should be generic with string keys for assoc and int keys for indexed.

**Comment by mockey** [comment]
> @:arrayAccess is not a type-level meta

That's how I understand the manual for core types. It says:
They are allowed to declare array access functions without expressions.
http://haxe.org/manual/types-abstract-core-type.html
Also see this:
https://github.com/HaxeFoundation/haxe/blob/development/src/typing/common.ml#L442
`[UsedOnEither [TAbstract;TAbstractField]]`
But maybe I'm mistaken...

> It should be added to methods. Did you try this?

Yes. see my issue:
You get an error: "Recursive array get method".

>  And In PHP you can push anything in array.

Yes, but "anything" still has a type T. I don't want a `NativeArray<T>`, I just want the T for the array functions, so that you can do of course:

``` haxe
var n = new NativeArray();
nat[1] = "foo";
nat["bar"] = [1,2,3];
```

But from my experience you can't really work with anything that's defined as Dynamic in Haxe. In this case it doesn't matter much, it seems, you get `Unknown<0>` when you use T instead of Dynamic, so I'm fine with Dynamic for the values if you prefer that.
I wanted to add some typing to NativeAssocArray but that's another topic...

> Also keys are dynamic, because in PHP you can use any scalar type as a key.

Yes, but according to this:
http://php.net/manual/en/language.types.array.php
they are cast to integer or string.
I don't see much sense in being able to have Bool or Float as keys when they are stored as Int.
And still, that's not Dynamic to me.

> But with NativeAssocArray and NativeIndexedArray i completely agree with you. They should be generic with string keys for assoc and int keys for indexed.

Well, that's something at least :-)

**Comment by RealyUniqueName** [comment]
If you have `NativeAssocArray` and `NativeIndexedArray` you can use them instead of `NativeArray`. Especially taking into account that after compilation all three will be the same thing in generated code :)
I just don't undertand why do you want to make `NativeArray` stricter if you have `NativeAssocArray<T>` and `NativeIndexedArray<T>` :)
What are the benefits? Am i missing something?

**Comment by mockey** [comment]
As I wrote, I'm fine with Dynamic for the value, there is no benefit in T here..
Dynamic for the key is just not correct, but I'll be fine with that, too.

**Comment by mockey** [comment]
I just saw that I get "Assertion failed Unexpected expression." with Dynamic but not with T :-)
But that's probably because it's not implemented yet...

**Comment by mockey** [comment]
Another thing: How do you want to handle access to Haxe Array? In the generator or implement ArrayAccess on PHP HxArray class?

**Comment by RealyUniqueName** [comment]
> I just saw that I get "Assertion failed Unexpected expression." with Dynamic but not with T :-) But that's probably because it's not implemented yet...

Yep

> Another thing: How do you want to handle access to Haxe Array? In the generator or implement ArrayAccess on PHP HxArray class?

Implementing `ArrayAccess` will slow down Haxe Array a lot. So i want to handle it in generator.

**Comment by mockey** [comment]
OK.

**Comment by mockey** [comment]
Any idea for iterator? Any convention for toString yet?
These are the two things missing in the implementation?

**Comment by RealyUniqueName** [comment]
> Dynamic for the key is just not correct

You're right, i completely missed this. But limiting keys to just `Int` and `String` is not correct too. Since `NativeArray` is a native type we have to support everything platform allows to do with this type.
We can try something like this:

``` haxe
typedef Scalar = EitherType<Int, EitherType<String, EitherType<Float, Bool>>>;
@:coreType @:runtimeValue abstract NativeArray {
  @:arrayAccess function get (key:Scalar) : Dynamic;
  @:arrayAccess function set (key:Scalar, value:Dynamic) : Dynamic;
}
```

**Comment by RealyUniqueName** [comment]
> Any idea for iterator? Any convention for toString yet?
> These are the two things missing in the implementation?

Since `NativeArray` will be an abstract, we can add fields `function toString()` and `function iterator() : NativeArrayIterator`. And make `NativeArrayIterator` completely inlineable.

**Comment by mockey** [comment]
> Since NativeString will be an abstract, we can add fields function toString() and function iterator() : NativeArrayIterator. And make NativeArrayIterator completely inlineable.

Not sure what you mean here.

**Comment by RealyUniqueName** [comment]
> Not sure what you mean here.

That was a typo. I meant `NativeArray`, not `NativeString`.
Or was you asking about Haxe `Array`?

**Comment by mockey** [comment]
About Haxe Array. I added a basic ArrayIterator for now. Can be optimised maybe.
I also meant Array.toString. Not sure what your plans are for that.
Preparing a PR now..
