### ISSUE TITLE
Global functions

### ISSUE THREAD

**Issue by mockey** [RealyUniqueName/haxe#43]
> As for global functions my thought is it's better to place them all in a single extern class like Global so that users with PHP background always know where to search for API of such function.

I'd prefer to have them separated, because they are just too numerous. I thought the way it is done in the reference could be adopted somehow:
http://php.net/manual/en/funcref.php
But I don't mind really. I can always add some aliases for me :-)
Do you want to keep the original PHP names then, like `array_filter`?

**Comment by RealyUniqueName** [comment]
I'd like to keep native platform things identical to what they are and how they implemented on that platform :)
So yes, i'd like to preserve their names and arguments the same as in PHP.

**Comment by mockey** [comment]
> i'd like to preserve their names and arguments the same as in PHP.

OK, I'll add the array functions I have so far to Global then.

**Comment by mockey** [comment]
Global.hx has spaces instead of tabs. Intentional?

**Comment by RealyUniqueName** [comment]
Mistake. I've pushed version with tabs instead.

**Comment by RealyUniqueName** [comment]
After a while it looks like having all native global function in one extern class is pretty convenient.
