### ISSUE TITLE
Cast

### ISSUE THREAD

**Issue by TheoSabattie** [RealyUniqueName/haxe#57]
Hi'',

An error happened when I tried to cast an instance to a class and that wasn't a castException
Main Class:

```
class Main 
{

    static function main() 
    {
        var test:Test   = new Test();
        var test2:Test2 = new Test2();

        cast(test, Test2).test404();
    }
}
```

Test2

```
class Test2
{
    private var test:String;
    private var test2:String;

    public function new(test:String = 'couocu', ?test2:String) 
    {
        this.test  = test;
        this.test2 = test2;
    }

    public function test404():Void {
        trace("test : " + test);
        trace("test : " + test2);
    }

}
```

Test

```
class Test extends Test2
{

    public function new(?test:String = "test", ?hercule:String) 
    {
        super();
    }

}
```

error:
`Fatal error: Uncaught ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Test2' does not have a method 'typedCast' in C:\Users\Theo Sabattie\Desktop\testPHP\bin\lib\php7\_Boot\HxClass.php:163 Stack trace: #0 [internal function]: php7\Boot::php7\{closure}(2, 'call_user_func_...', 'C:\\Users\\Theo ...', 163, Array) #1 C:\Users\Theo Sabattie\Desktop\testPHP\bin\lib\php7\_Boot\HxClass.php(163): call_user_func_array('Test2::typedCas...', Array) #2 C:\Users\Theo Sabattie\Desktop\testPHP\bin\lib\Main.php(11): php7\_Boot\HxClass->__call('typedCast', Array) #3 C:\Users\Theo Sabattie\Desktop\testPHP\bin\index.php(12): Main::main() #4 {main} thrown in C:\Users\Theo Sabattie\Desktop\testPHP\bin\lib\php7\_Boot\HxClass.php on line 163`

generated function:

```
static public function main ()
{
    (Boot::getClass('\\Test2')->typedCast(new \Test()))->test404();
}
```

typedCast does not exist on HxClass, that calls __call magic function.
There is "tryCast" function on HxClass but an argument is missing (targeted type).

Thanks

**Comment by RealyUniqueName** [comment]
Thanks for report.
Fixed in 4c1b447
