### ISSUE TITLE
Exception, file is not generated

### ISSUE THREAD

**Issue by TheoSabattie** [RealyUniqueName/haxe#58]
Hi',

```
class Main 
{
    static function main() 
    {
        throw "test";
        }
}
```

Generated code:

```
<?php
use \php7\Boot;
use \php7\HException;

class Main
{
    /**
     * @return void
     */
    static public function main ()
    {
        throw new HException("test");
    }

```

error:

`Fatal error: Uncaught Error: Class 'php7\HException' not found in C:\Users\Theo Sabattie\Desktop\testPHP\bin\lib\php7\Boot.php:433 Stack trace: #0 C:\Users\Theo Sabattie\Desktop\testPHP\bin\lib\Main.php(11): php7\Boot::typedCast(Object(php7\_Boot\HxClass), Object(Test2)) #1 C:\Users\Theo Sabattie\Desktop\testPHP\bin\index.php(12): Main::main() #2 {main} thrown in C:\Users\Theo Sabattie\Desktop\testPHP\bin\lib\php7\Boot.php on line 433`

HException.php does not exist//is not generated;

![alt text](http://puu.sh/r1aua/6fb2b26caf.png)

Thanks

**Comment by RealyUniqueName** [comment]
Fixed in 3b3dc77
