### ISSUE TITLE
Invoke native PHP class constants

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#60]
Right now there is no way (except untyped) to access PHP class constants from Haxe code.
Perhaps some meta for extern static vars can tell compiler that var is actually a class constant.

**Comment by mockey** [comment]
Yes, there should be a special metadata for that, I'd say.

**Comment by RealyUniqueName** [comment]
_Implemented in 19c773f_
Meta for externs to generate `static var` fields as class constants: `@:phpClassConst`
Example: https://github.com/RealyUniqueName/haxe/blob/php7/std/php7/reflection/ReflectionClass.hx#L7
