### ISSUE TITLE
Class<T> implementation

### ISSUE THREAD

**Issue by RealyUniqueName** [RealyUniqueName/haxe#9]
Right now `Class<T>`  is generated as instances of special `HxClass` class (in 48a9d20).

Perhaps it should be changed to plain string which is simple, easy to maintain and has almost zero runtime cost. However strings can lead to confusions like this one:

``` haxe
var str = "\\some\\pack\\MyClass";
var d : Dynamic = str;

d.someMehod();
//Should this fail with "cannot call `someMethod()` on non-object"?
//Or is it ok to invoke static `\some\pack\MyClass::someMethod()` in such cases?
```

Also keep in mind that native php class names can contain `/` and `@` chars ([see examples output and Note section](http://php.net/manual/en/language.oop5.anonymous.php))

_Implemented as `HxClass` in  48a9d20_

**Comment by mockey** [comment]
As far as I remember a class implementation is needed for handling dynamics. There were many cases that lead to crazy contortions in PHP.  I'll try to dig out the old code I wrote with Simn last year...

**Comment by RealyUniqueName** [comment]
Right now i've implemented something simiral to qtypes 
Old  Haxe->PHP implementation: https://github.com/RealyUniqueName/haxe/blob/php7/std/php/Boot.hx#L871
Current:
https://github.com/RealyUniqueName/haxe/commit/48a9d2088c11fc893d55f76fbe1ebc19c8c41fe0#diff-80ee397f373d01f7afcae0937f8aff3aR78

In every place where `Class<T>` is used as a value `Boot::getClass('\\some\\MyClass')` is generated (which returns an instance of `HxClass`)

**Comment by mockey** [comment]
I see. I'll have a more detailed look at the code tomorrow.
